<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;A. Belcaid">

<title>Modern Vision Architectures – Deep Learning</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-095245003bb80bd2beb305de39928752.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2e7c9b518fe54fcaa4a8b379123416fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/mark.svg" alt="" class="navbar-logo light-content">
    <img src="../../assets/mark.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Deep Learning</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../notes.html"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../logistics.html"> 
<span class="menu-text">Logistics</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/anassBelcaid/deeplearning-course"> <i class="bi bi-github" role="img" aria-label="Course repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#modern-vision-architectures" id="toc-modern-vision-architectures" class="nav-link active" data-scroll-target="#modern-vision-architectures">Modern Vision Architectures</a></li>
  <li><a href="#a-first-level-map-of-the-lecture" id="toc-a-first-level-map-of-the-lecture" class="nav-link" data-scroll-target="#a-first-level-map-of-the-lecture">A first-level map of the lecture</a></li>
  <li><a href="#why-architecture-becomes-a-design-problem-1" id="toc-why-architecture-becomes-a-design-problem-1" class="nav-link" data-scroll-target="#why-architecture-becomes-a-design-problem-1">01 · Why architecture becomes a design problem</a>
  <ul class="collapse">
  <li><a href="#yesterdays-cnn-meets-a-larger-world" id="toc-yesterdays-cnn-meets-a-larger-world" class="nav-link" data-scroll-target="#yesterdays-cnn-meets-a-larger-world">Yesterday’s CNN meets a larger world</a></li>
  <li><a href="#audit-the-tempting-design" id="toc-audit-the-tempting-design" class="nav-link" data-scroll-target="#audit-the-tempting-design">Audit the tempting design</a></li>
  <li><a href="#every-pool-spends-spatial-resolution" id="toc-every-pool-spends-spatial-resolution" class="nav-link" data-scroll-target="#every-pool-spends-spatial-resolution">Every pool spends spatial resolution</a></li>
  <li><a href="#capacity-can-accumulate-in-the-wrong-place" id="toc-capacity-can-accumulate-in-the-wrong-place" class="nav-link" data-scroll-target="#capacity-can-accumulate-in-the-wrong-place">Capacity can accumulate in the wrong place</a></li>
  <li><a href="#a-deeper-hypothesis-should-not-be-worseshould-it" id="toc-a-deeper-hypothesis-should-not-be-worseshould-it" class="nav-link" data-scroll-target="#a-deeper-hypothesis-should-not-be-worseshould-it">A deeper hypothesis should not be worse—should it?</a></li>
  <li><a href="#three-pressures-define-the-design-brief" id="toc-three-pressures-define-the-design-brief" class="nav-link" data-scroll-target="#three-pressures-define-the-design-brief">Three pressures define the design brief</a></li>
  </ul></li>
  <li><a href="#depth-through-repeated-small-blocks" id="toc-depth-through-repeated-small-blocks" class="nav-link" data-scroll-target="#depth-through-repeated-small-blocks">02 · Depth through repeated small blocks</a>
  <ul class="collapse">
  <li><a href="#alexnet-the-reference-recipe" id="toc-alexnet-the-reference-recipe" class="nav-link" data-scroll-target="#alexnet-the-reference-recipe">AlexNet: the reference recipe</a></li>
  <li><a href="#vgg-turns-architecture-design-into-an-experiment" id="toc-vgg-turns-architecture-design-into-an-experiment" class="nav-link" data-scroll-target="#vgg-turns-architecture-design-into-an-experiment">VGG turns architecture design into an experiment</a></li>
  <li><a href="#one-vgg-block-becomes-the-design-unit" id="toc-one-vgg-block-becomes-the-design-unit" class="nav-link" data-scroll-target="#one-vgg-block-becomes-the-design-unit">One VGG block becomes the design unit</a></li>
  <li><a href="#from-alexnets-sequence-to-vggs-grammar" id="toc-from-alexnets-sequence-to-vggs-grammar" class="nav-link" data-scroll-target="#from-alexnets-sequence-to-vggs-grammar">From AlexNet’s sequence to VGG’s grammar</a></li>
  <li><a href="#the-architecture-becomes-a-short-specification" id="toc-the-architecture-becomes-a-short-specification" class="nav-link" data-scroll-target="#the-architecture-becomes-a-short-specification">The architecture becomes a short specification</a></li>
  <li><a href="#vggs-legacyand-its-unfinished-business" id="toc-vggs-legacyand-its-unfinished-business" class="nav-link" data-scroll-target="#vggs-legacyand-its-unfinished-business">VGG’s legacy—and its unfinished business</a></li>
  <li><a href="#nin-fixes-what-vgg-leaves-expensive" id="toc-nin-fixes-what-vgg-leaves-expensive" class="nav-link" data-scroll-target="#nin-fixes-what-vgg-leaves-expensive">NiN fixes what VGG leaves expensive</a></li>
  <li><a href="#a-nin-block-learns-within-each-location" id="toc-a-nin-block-learns-within-each-location" class="nav-link" data-scroll-target="#a-nin-block-learns-within-each-location">A NiN block learns within each location</a></li>
  <li><a href="#nin-ends-with-class-mapsnot-a-dense-head" id="toc-nin-ends-with-class-mapsnot-a-dense-head" class="nav-link" data-scroll-target="#nin-ends-with-class-mapsnot-a-dense-head">NiN ends with class maps—not a dense head</a></li>
  <li><a href="#the-complete-nin-module-mirrors-the-figure" id="toc-the-complete-nin-module-mirrors-the-figure" class="nav-link" data-scroll-target="#the-complete-nin-module-mirrors-the-figure">The complete NiN module mirrors the figure</a></li>
  <li><a href="#nin-changes-both-the-block-and-the-head" id="toc-nin-changes-both-the-block-and-the-head" class="nav-link" data-scroll-target="#nin-changes-both-the-block-and-the-head">NiN changes both the block and the head</a></li>
  </ul></li>
  <li><a href="#branching-across-spatial-scales-1" id="toc-branching-across-spatial-scales-1" class="nav-link" data-scroll-target="#branching-across-spatial-scales-1">03 · Branching across spatial scales</a>
  <ul class="collapse">
  <li><a href="#one-inputfour-receptive-field-choices" id="toc-one-inputfour-receptive-field-choices" class="nav-link" data-scroll-target="#one-inputfour-receptive-field-choices">One input—four receptive-field choices</a></li>
  <li><a href="#the-1times1-layers-are-capacity-valves" id="toc-the-1times1-layers-are-capacity-valves" class="nav-link" data-scroll-target="#the-1times1-layers-are-capacity-valves">The <span class="math inline">\(1\times1\)</span> layers are capacity valves</a></li>
  <li><a href="#the-diagram-becomes-an-inception-module" id="toc-the-diagram-becomes-an-inception-module" class="nav-link" data-scroll-target="#the-diagram-becomes-an-inception-module">The diagram becomes an Inception module</a></li>
  <li><a href="#once-understood-compress-the-block" id="toc-once-understood-compress-the-block" class="nav-link" data-scroll-target="#once-understood-compress-the-block">Once understood, compress the block</a></li>
  <li><a href="#nine-blocks-become-one-googlenet-class" id="toc-nine-blocks-become-one-googlenet-class" class="nav-link" data-scroll-target="#nine-blocks-become-one-googlenet-class">Nine blocks become one GoogLeNet class</a></li>
  <li><a href="#googlenet-gains-scale-diversityat-a-cost" id="toc-googlenet-gains-scale-diversityat-a-cost" class="nav-link" data-scroll-target="#googlenet-gains-scale-diversityat-a-cost">GoogLeNet gains scale diversity—at a cost</a></li>
  </ul></li>
  <li><a href="#learning-residual-corrections-1" id="toc-learning-residual-corrections-1" class="nav-link" data-scroll-target="#learning-residual-corrections-1">04 · Learning residual corrections</a>
  <ul class="collapse">
  <li><a href="#learn-the-correctionnot-the-whole-transformation" id="toc-learn-the-correctionnot-the-whole-transformation" class="nav-link" data-scroll-target="#learn-the-correctionnot-the-whole-transformation">Learn the correction—not the whole transformation</a></li>
  <li><a href="#one-block-two-shortcut-policies" id="toc-one-block-two-shortcut-policies" class="nav-link" data-scroll-target="#one-block-two-shortcut-policies">One block, two shortcut policies</a></li>
  <li><a href="#addition-imposes-a-shape-contract" id="toc-addition-imposes-a-shape-contract" class="nav-link" data-scroll-target="#addition-imposes-a-shape-contract">Addition imposes a shape contract</a></li>
  </ul></li>
  <li><a href="#reusing-every-feature-with-densenet" id="toc-reusing-every-feature-with-densenet" class="nav-link" data-scroll-target="#reusing-every-feature-with-densenet">05 · Reusing every feature with DenseNet</a>
  <ul class="collapse">
  <li><a href="#a-dense-layer-appendsit-does-not-replace" id="toc-a-dense-layer-appendsit-does-not-replace" class="nav-link" data-scroll-target="#a-dense-layer-appendsit-does-not-replace">A dense layer appends—it does not replace</a></li>
  <li><a href="#watch-the-feature-bank-grow" id="toc-watch-the-feature-bank-grow" class="nav-link" data-scroll-target="#watch-the-feature-bank-grow">Watch the feature bank grow</a></li>
  <li><a href="#cool-the-representation-before-it-grows-again" id="toc-cool-the-representation-before-it-grows-again" class="nav-link" data-scroll-target="#cool-the-representation-before-it-grows-again">Cool the representation before it grows again</a></li>
  <li><a href="#the-implementation-mirrors-the-equation" id="toc-the-implementation-mirrors-the-equation" class="nav-link" data-scroll-target="#the-implementation-mirrors-the-equation">The implementation mirrors the equation</a></li>
  <li><a href="#feature-reuse-buys-efficiencybut-stores-activations" id="toc-feature-reuse-buys-efficiencybut-stores-activations" class="nav-link" data-scroll-target="#feature-reuse-buys-efficiencybut-stores-activations">Feature reuse buys efficiency—but stores activations</a></li>
  </ul></li>
  <li><a href="#the-architecture-toolkit-1" id="toc-the-architecture-toolkit-1" class="nav-link" data-scroll-target="#the-architecture-toolkit-1">06 · The architecture toolkit</a></li>
  <li><a href="#compose-for-the-task" id="toc-compose-for-the-task" class="nav-link" data-scroll-target="#compose-for-the-task">07 · Compose for the task</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modern Vision Architectures</h1>
<p class="subtitle lead">Designing depth, information flow, and reuse</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;A. Belcaid </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="modern-vision-architectures" class="level2 deck-title">
<h2 class="deck-title anchored" data-anchor-id="modern-vision-architectures">Modern Vision Architectures</h2>
<div class="deck-title-grid">
<div class="deck-title-copy">
<p><span class="eyebrow">CHAPTER 08 · LEARNING FROM IMAGES</span></p>
<section id="designing-depth-information-flow-and-reuse" class="level3">
<h3 class="anchored" data-anchor-id="designing-depth-information-flow-and-reuse">Designing depth, information flow, and reuse</h3>
<p>How can a vision model become deeper and more capable without becoming impossible to optimize or deploy?</p>
<p><span class="deck-author">Dr.&nbsp;A. Belcaid</span></p>
</section>
</div>
<div class="deck-title-art modern-vision-hero">
<p><img src="assets/modern-vision-hero.png" class="img-fluid" alt="A stylized image tensor passes through modular feature blocks while a skip path carries information around the middle transformations."></p>
</div>
</div>
<div class="notes">
<p>The image previews the lecture’s design problem rather than one named architecture. The main path becomes deeper and more abstract; the arc preserves an earlier signal and merges it back later. Ask students what can go wrong as we keep stacking the convolutional blocks from Chapter 7. This lecture studies architectural answers: disciplined repetition, channel mixing, multi-scale branching, residual information flow, dense feature reuse, and task-driven composition.</p>
</div>
</section>
<section id="a-first-level-map-of-the-lecture" class="level2">
<h2 class="anchored" data-anchor-id="a-first-level-map-of-the-lecture">A first-level map of the lecture</h2>
<div class="architecture-toc">
<div class="architecture-toc-item pressure-item">
<p><span>01</span></p>
<section id="why-architecture-becomes-a-design-problem" class="level3">
<h3 class="anchored" data-anchor-id="why-architecture-becomes-a-design-problem">Why architecture becomes a design problem</h3>
</section>
</div>
<div class="architecture-toc-item blocks-item">
<p><span>02</span></p>
<section id="depth-through-repeated-blocks" class="level3">
<h3 class="anchored" data-anchor-id="depth-through-repeated-blocks">Depth through repeated blocks</h3>
</section>
</div>
<div class="architecture-toc-item branch-item">
<p><span>03</span></p>
<section id="branching-across-spatial-scales" class="level3">
<h3 class="anchored" data-anchor-id="branching-across-spatial-scales">Branching across spatial scales</h3>
</section>
</div>
<div class="architecture-toc-item residual-item">
<p><span>04</span></p>
<section id="learning-residual-corrections" class="level3">
<h3 class="anchored" data-anchor-id="learning-residual-corrections">Learning residual corrections</h3>
</section>
</div>
<div class="architecture-toc-item dense-item">
<p><span>05</span></p>
<section id="reusing-earlier-features" class="level3">
<h3 class="anchored" data-anchor-id="reusing-earlier-features">Reusing earlier features</h3>
</section>
</div>
<div class="architecture-toc-item augmentation-item">
<p><span>06</span></p>
<section id="the-architecture-toolkit" class="level3">
<h3 class="anchored" data-anchor-id="the-architecture-toolkit">The architecture toolkit</h3>
</section>
</div>
<div class="architecture-toc-item transfer-item">
<p><span>07</span></p>
<section id="composing-a-task-specific-network" class="level3">
<h3 class="anchored" data-anchor-id="composing-a-task-specific-network">Composing a task-specific network</h3>
</section>
</div>
</div>
<div class="notes">
<p>Keep this roadmap at the level of transferable design ideas. We first establish why a naive chain of convolution and pooling does not scale cleanly: resolution may disappear too quickly, wide kernels and dense heads spend parameters heavily, and deeper chains become harder to optimize. VGG supplies the concrete case for depth through repeated small padded convolutions <span class="citation" data-cites="simonyan2015vgg">(Simonyan and Zisserman 2015)</span>. ResNet introduces residual addition <span class="citation" data-cites="he2016resnet">(He et al. 2016)</span>, while DenseNet uses dense concatenation to reuse earlier features <span class="citation" data-cites="huang2017densenet">(Huang et al. 2017)</span>. The final two sections turn the historical architectures into a reusable toolkit, then compose several mechanisms around one task specification.</p>
</div>
</section>
<section id="why-architecture-becomes-a-design-problem-1" class="level1 section-slide architecture-section pressure-section" data-section-progress="1 / 7" style="--section-progress:14.286%">
<h1 class="section-slide architecture-section pressure-section" data-section-progress="1 / 7" style="--section-progress:14.286%">01 · Why architecture becomes a design problem</h1>
<section id="yesterdays-cnn-meets-a-larger-world" class="level2">
<h2 class="anchored" data-anchor-id="yesterdays-cnn-meets-a-larger-world">Yesterday’s CNN meets a larger world</h2>
<div class="scale-up-stage">
<div class="scale-up-model">
<span>THE FAMILIAR MODEL</span> <strong>two convolution blocks</strong>
<div class="mini-pipeline" aria-label="A small image passes through two convolution and pooling blocks into a classifier.">
<i>32²</i><b>conv<br>pool</b><i>16²</i><b>conv<br>pool</b><i>8²</i><b>linear</b><i>10</i>
</div>
<p><small>CIFAR-10 · 32 × 32 RGB · 10 classes</small></p>
</div>
<div class="scale-up-arrow fragment" data-fragment-index="0" aria-hidden="true">
→
</div>
<div class="scale-up-brief fragment" data-fragment-index="0">
<span>NEW DESIGN BRIEF</span> <strong>recognize 1,000 categories</strong>
<div>
<b>224 × 224</b><small>larger images</small>
</div>
<div>
<b>1.2M</b><small>training examples</small>
</div>
<div>
<b>1,000</b><small>output classes</small>
</div>
</div>
</div>
<div class="scale-up-question fragment" data-fragment-index="1">
<p><span>YOUR PREDICTION</span> <strong>Can we scale by repeating the same block—convolution, pooling, repeat?</strong></p>
</div>
<p class="source-note">
Large-scale setting: ImageNet / ILSVRC classification <span class="citation" data-cites="deng2009imagenet he2016resnet">(Deng et al. 2009; He et al. 2016)</span>.
</p>
<div class="notes">
<p>Retrieve the exact model students read at the end of Chapter 7, then change the problem rather than beginning with an architecture name. The 1.2 million count refers to the ILSVRC classification training set. Reveal the new brief and ask for a show of hands: repeat the familiar block, redesign it, or unsure. Do not judge the answers yet. This section will audit that tempting first proposal.</p>
</div>
</section>
<section id="audit-the-tempting-design" class="level2">
<h2 class="anchored" data-anchor-id="audit-the-tempting-design">Audit the tempting design</h2>
<div class="audit-layout">
<div class="audit-chain">
<span>PROPOSED PLAIN CNN</span>
<div>
<b>INPUT</b><strong>224 × 224 × 3</strong>
</div>
<i>↓</i>
<div>
<b>BLOCK × 5</b><strong>Conv · ReLU · Pool /2</strong>
</div>
<i>↓</i>
<div>
<b>FEATURES</b><strong>512 × ? × ?</strong>
</div>
<i>↓</i>
<div>
<b>HEAD</b><strong>Flatten · Linear 4096</strong>
</div>
</div>
<div class="audit-task">
<span>EXACT TASK</span> <strong>Audit the design before training it.</strong>
<div>
<b>1</b><small>What spatial size remains after five pools?</small>
</div>
<div>
<b>2</b><small>How many values enter the first dense layer?</small>
</div>
<div>
<b>3</b><small>How many weights does that dense layer own?</small>
</div>
</div>
</div>
<div class="pause-panel architecture-audit-pause fragment fade-out" data-fragment-index="0">
<p><strong>PAUSE · 90 seconds</strong><span>Track only <span class="math inline">\(H\times W\)</span> first; restore the 512 channels at the end.</span></p>
</div>
<div class="audit-solution fragment" data-fragment-index="0">
<span>WORKED AUDIT</span>
<div>
<strong><span class="math inline">\(224/2^5=7\)</span></strong><small>final spatial size</small>
</div>
<div>
<strong><span class="math inline">\(512\times7\times7=25{,}088\)</span></strong><small>flattened values</small>
</div>
<div>
<strong><span class="math inline">\(25{,}088\times4{,}096\approx102.8\text{M}\)</span></strong><small>weights in one layer</small>
</div>
</div>
<div class="notes">
<p>Honor the pause. Students know pooling geometry and dense-layer parameter counting from earlier chapters, so this is retrieval in service of a new design question. The computation deliberately resembles the first VGG dense layer, but do not name VGG yet. Reveal the complete solution on one advancement. Bias parameters add only 4,096 and do not change the conclusion.</p>
</div>
</section>
<section id="every-pool-spends-spatial-resolution" class="level2">
<h2 class="anchored" data-anchor-id="every-pool-spends-spatial-resolution">Every pool spends spatial resolution</h2>
<div class="resolution-question">
<span>TRACE ONE SMALL OBJECT</span><strong>At which stage does its precise location become difficult to preserve?</strong>
</div>
<div class="resolution-ledger">
<div class="resolution-stage r224">
<span>INPUT</span><strong>224²</strong>
<div class="tiny-object object-1" aria-label="A small object occupies a small region of a 224 by 224 representation.">

</div>
<p><small>1×</small></p>
</div>
<p><b>→</b></p>
<div class="resolution-stage r112 fragment">
<span>POOL 1</span><strong>112²</strong>
<div class="tiny-object object-2">

</div>
<p><small>½ width</small></p>
</div>
<p><b class="fragment">→</b></p>
<div class="resolution-stage r56 fragment">
<span>POOL 2</span><strong>56²</strong>
<div class="tiny-object object-3">

</div>
<p><small>¼ width</small></p>
</div>
<p><b class="fragment">→</b></p>
<div class="resolution-stage r28 fragment">
<span>POOL 3</span><strong>28²</strong>
<div class="tiny-object object-4">

</div>
<p><small>⅛ width</small></p>
</div>
<p><b class="fragment">→</b></p>
<div class="resolution-stage r7 fragment">
<span>POOL 5</span><strong>7²</strong>
<div class="tiny-object object-5">

</div>
<p><small>1⁄32 width</small></p>
</div>
</div>
<div class="resolution-verdict fragment">
<p><span>DESIGN DECISION</span><strong>Downsampling buys context and efficiency—but it spends localization detail.</strong></p>
</div>
<div class="notes">
<p>Ask students to follow the orange object, not merely recite the dimensions. Each displayed square is schematic: it represents the resolution budget rather than literal pixels. Pooling is not a mistake; reducing resolution increases the effective field of view and lowers computation. The architectural question is when to spend that budget. Segmentation and detection will make the cost of localization loss especially visible in Chapter 9.</p>
</div>
</section>
<section id="capacity-can-accumulate-in-the-wrong-place" class="level2">
<h2 class="anchored" data-anchor-id="capacity-can-accumulate-in-the-wrong-place">Capacity can accumulate in the wrong place</h2>
<div class="parameter-balance">
<div class="parameter-map">
<span>WHERE DO THE WEIGHTS LIVE?</span>
<div class="feature-bank" aria-label="A bank of 512 feature maps, each 7 by 7.">
<b>512</b><i>feature maps</i><strong>7 × 7</strong>
</div>
<div class="flatten-mark">
flatten → <strong>25,088</strong>
</div>
<div class="dense-bank">
<b>4,096</b><i>dense units</i>
</div>
</div>
<div class="parameter-reckoning">
<span>ONE MATRIX</span>
<p>
<span class="math inline">\(25{,}088\times4{,}096\)</span>
</p>
<strong class="fragment">102,760,448 weights</strong> <small class="fragment">before its bias—and before the next dense layer</small>
<div class="parameter-question fragment">
Which representation owns most of the hypothesis: the spatial feature extractor or the classifier head?
</div>
</div>
</div>
<div class="parameter-verdict fragment">
<p>More parameters do not automatically mean better features. <strong>Placement matters.</strong></p>
</div>
<div class="notes">
<p>Let students estimate the order of magnitude before revealing the exact multiplication. The question is about parameter allocation, not an assertion that dense layers are universally wrong. Historically, large dense heads were viable and influential. Later designs increasingly replace them with pooling and small classifiers so capacity is concentrated in learned spatial features. This slide sets up that later evolution without jumping ahead to its solution.</p>
</div>
</section>
<section id="a-deeper-hypothesis-should-not-be-worseshould-it" class="level2">
<h2 class="anchored" data-anchor-id="a-deeper-hypothesis-should-not-be-worseshould-it">A deeper hypothesis should not be worse—should it?</h2>
<div class="depth-thought-experiment">
<div class="depth-model shallow-model">
<span>20-LAYER PLAIN CNN</span>
<div class="depth-stack">
20
</div>
<p><small>learn a classifier <span class="math inline">\(f(x)\)</span></small></p>
</div>
<div class="depth-logic">
<span>CONSTRUCTION ARGUMENT</span>
<p>
Copy the 20 learned layers.
</p>
<strong>Set the 36 added layers to identity mappings.</strong>
<p class="fragment">
Then the deeper model can represent the same function.
</p>
</div>
<div class="depth-model deep-model fragment">
<span>56-LAYER PLAIN CNN</span>
<div class="depth-stack">
56
</div>
<p><small>contains at least that candidate solution</small></p>
</div>
</div>
<div class="depth-prediction fragment">
<p><span>PREDICT BEFORE THE DATA</span><strong>Should its training error be lower, equal, or higher?</strong></p>
</div>
<div class="notes">
<p>This argument is adapted from the motivation in He et al. <span class="citation" data-cites="he2016resnet">(He et al. 2016)</span>. Be precise: it establishes the existence of a candidate solution for a suitably constructed deeper counterpart; it does not claim that ordinary nonlinear layers are automatically initialized as exact identities. Ask students to vote lower, equal, or higher. Their optimization algorithm must still find the useful parameters.</p>
</div>
</section>
<section id="three-pressures-define-the-design-brief" class="level2">
<h2 class="anchored" data-anchor-id="three-pressures-define-the-design-brief">Three pressures define the design brief</h2>
<div class="design-brief-grid">
<div class="design-pressure pressure-space">
<span>01 · REPRESENTATION</span>
<div class="pressure-icon spatial-icon" aria-hidden="true">

</div>
<p><strong>When should resolution shrink?</strong> <small>Preserve detail long enough; buy context and efficiency deliberately.</small></p>
</div>
<div class="design-pressure pressure-capacity fragment">
<span>02 · CAPACITY</span>
<div class="pressure-icon capacity-icon" aria-hidden="true">

</div>
<p><strong>Where should parameters live?</strong> <small>Spend capacity on reusable features, not accidental bottlenecks.</small></p>
</div>
<div class="design-pressure pressure-flow fragment">
<span>03 · OPTIMIZATION</span>
<div class="pressure-icon flow-icon" aria-hidden="true">

</div>
<p><strong>How should information travel?</strong> <small>Make useful deep solutions reachable by gradient-based training.</small></p>
</div>
</div>
<div class="design-bridge fragment">
<p><span>NEXT</span><strong>Repeated small blocks make depth systematic.</strong><i>→ VGG</i></p>
</div>
<div class="notes">
<p>Use this as the section synthesis. Architecture is part of the hypothesis: it determines representation geometry, parameter allocation, and information flow. The three pressures came from concrete evidence, not a taxonomy. Map them forward without giving away the full lecture: VGG makes depth systematic, ResNet changes information flow, and DenseNet makes feature reuse explicit. The next section begins with VGG and asks how repeated small kernels can grow depth economically.</p>
</div>
</section>
</section>
<section id="depth-through-repeated-small-blocks" class="level1 section-slide architecture-section blocks-section" data-section-progress="2 / 7" style="--section-progress:28.571%">
<h1 class="section-slide architecture-section blocks-section" data-section-progress="2 / 7" style="--section-progress:28.571%">02 · Depth through repeated small blocks</h1>
<section id="alexnet-the-reference-recipe" class="level2">
<h2 class="anchored" data-anchor-id="alexnet-the-reference-recipe">AlexNet: the reference recipe</h2>
<div class="alexnet-schematic">
<p><img src="assets/alexnet-layer-stack.svg" alt="AlexNet represented as a narrowing vertical stack of convolution, pooling, and fully connected layers. Read from the bottom upward."></p>
</div>
<div class="alexnet-schematic-guide">
<p><span>READ BOTTOM → TOP</span> <strong>Which components repeat—and which design choices keep changing?</strong> <small class="fragment">Convolution and pooling repeat, but kernel sizes shift from <span class="math inline">\(11\times11\)</span> to <span class="math inline">\(5\times5\)</span> to <span class="math inline">\(3\times3\)</span>.</small></p>
</div>
<p class="source-note">
Course-made reconstruction of AlexNet from Krizhevsky, Sutskever &amp; Hinton <span class="citation" data-cites="krizhevsky2012imagenet">(Krizhevsky et al. 2012)</span>. Bar width qualitatively indicates the reduction of spatial resolution.
</p>
<div class="notes">
<p>Let students read the figure before interpreting it. The layer bars deliberately follow the compact graphical grammar of the supplied AlexNet–VGG reference: one bar per operation, a distinct color for pooling, and a bottom-to-top computational path. Ask students to identify the recurring components first. Then reveal the irregularity that VGG will address: AlexNet changes kernel sizes and uses an aggressive stride-four entrance before settling on three-by-three convolutions.</p>
</div>
</section>
<section id="vgg-turns-architecture-design-into-an-experiment" class="level2">
<h2 class="anchored" data-anchor-id="vgg-turns-architecture-design-into-an-experiment">VGG turns architecture design into an experiment</h2>
<div class="vgg-paper-intro">
<div class="vgg-paper-figure">
<p><img src="assets/vgg-paper-table1.png" alt="Table 1 from the original VGG paper, comparing network configurations A through E as depth increases from 11 to 19 learned layers."> <small>Original architecture configurations · Table 1</small></p>
</div>
<div class="vgg-paper-ideas">
<span>SIMONYAN &amp; ZISSERMAN · 2014</span> <strong>Very Deep Convolutional Networks for Large-Scale Image Recognition</strong>
<div>
<b>STANDARDIZE</b><small>Replace changing kernel recipes with padded <span class="math inline">\(3\times3\)</span> convolutions.</small>
</div>
<div class="fragment">
<b>ISOLATE DEPTH</b><small>Compare configurations built from the same disciplined design rules.</small>
</div>
<div class="fragment">
<b>DELAY DOWNSAMPLING</b><small>Apply several convolutions before spending resolution on pooling.</small>
</div>
</div>
</div>
<div class="vgg-paper-question fragment">
<p><span>RESEARCH QUESTION</span><strong>Can a deeper, regular stack outperform a shallower sequence of special cases?</strong></p>
</div>
<p class="source-note">
Original Table 1 and design analysis from Simonyan &amp; Zisserman <span class="citation" data-cites="simonyan2015vgg">(Simonyan and Zisserman 2015)</span>. See also the <a href="https://anassbelcaid.github.io/deeplearning/modernconv/">2024 course chapter</a>.
</p>
<div class="notes">
<p>Introduce VGG as a research program rather than merely a named architecture. The table is the paper’s experimental design: configurations A through E increase learned depth while retaining a disciplined local recipe. Ask students what must remain fixed if depth is the variable of interest. Reveal the three ideas only after their answers. The crucial abstraction is to stop designing every layer as a special case and begin composing repeated blocks.</p>
</div>
</section>
<section id="one-vgg-block-becomes-the-design-unit" class="level2">
<h2 class="anchored" data-anchor-id="one-vgg-block-becomes-the-design-unit">One VGG block becomes the design unit</h2>
<div class="vgg-block-code-layout">
<div class="vgg-block-native-figure">
<p><img src="assets/vgg-block-schematic.svg" alt="A VGG block shown as a labeled plate containing repeated padded three by three convolution and ReLU layers, followed by two by two max pooling."></p>
</div>
<div class="light-code-editor vgg-native-editor">
<div class="editor-bar">
<span>PYTORCH · BLOCK FACTORY</span><strong>vgg.py</strong>
</div>
<pre><code><span class="py-kw">def</span> <span class="py-fn">vgg_block</span>(<span class="py-param">num_convs</span>, <span class="py-param">out_channels</span>):
    layers <span class="py-punc">=</span> []

    <span class="py-kw">for</span> _ <span class="py-kw">in</span> <span class="py-call">range</span>(num_convs):
        layers.<span class="py-call">extend</span>([
            <span class="py-mod">nn</span>.<span class="py-call">LazyConv2d</span>(
                out_channels,
                <span class="py-param">kernel_size</span><span class="py-punc">=</span><span class="py-num">3</span>, <span class="py-param">padding</span><span class="py-punc">=</span><span class="py-num">1</span>
            ),
            <span class="py-mod">nn</span>.<span class="py-call">ReLU</span>(),
        ])

    layers.<span class="py-call">append</span>(
        <span class="py-mod">nn</span>.<span class="py-call">MaxPool2d</span>(<span class="py-param">kernel_size</span><span class="py-punc">=</span><span class="py-num">2</span>, <span class="py-param">stride</span><span class="py-punc">=</span><span class="py-num">2</span>)
    )
    <span class="py-kw">return</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(*layers)</code></pre>
</div>
</div>
<div class="vgg-block-contract fragment">
<p><span>BLOCK CONTRACT</span><strong><span class="math inline">\(H\times W\)</span> is preserved inside the plate</strong><b>→</b><strong>pooling returns <span class="math inline">\(H/2\times W/2\)</span> once</strong></p>
</div>
<p class="source-note">
Block design from Simonyan &amp; Zisserman <span class="citation" data-cites="simonyan2015vgg">(Simonyan and Zisserman 2015)</span>; PyTorch implementation adapted from the instructor’s 2024 course chapter.
</p>
<div class="notes">
<p>Trace the figure and code together from bottom to top. The loop is the plate: it repeats the same spatially preserving operation. Padding one keeps height and width unchanged for every three-by-three convolution. Pooling sits outside the repetition and therefore halves resolution exactly once per block. Ask students which two arguments define a block; the answer is its repetition count and output channel count.</p>
</div>
</section>
<section id="from-alexnets-sequence-to-vggs-grammar" class="level2">
<h2 class="anchored" data-anchor-id="from-alexnets-sequence-to-vggs-grammar">From AlexNet’s sequence to VGG’s grammar</h2>
<div class="vgg-three-column-figure">
<p><img src="assets/vgg-three-column-comparison.svg" alt="Three-column comparison showing the full VGG model composed from five blocks, the repeated layers inside one VGG block, and AlexNet as a reference sequence whose kernel choices change by stage."></p>
</div>
<div class="vgg-comparison-reading fragment">
<p><span>THE ARCHITECTURAL MOVE</span> <strong>AlexNet chooses layers one by one.</strong> <b>→</b> <strong>VGG defines one block, then scales by composition.</strong></p>
</div>
<p class="source-note">
Course-made comparison derived from Krizhevsky et al. <span class="citation" data-cites="krizhevsky2012imagenet">(Krizhevsky et al. 2012)</span> and Simonyan &amp; Zisserman <span class="citation" data-cites="simonyan2015vgg">(Simonyan and Zisserman 2015)</span>.
</p>
<div class="notes">
<p>Read the columns in the requested order. Start with the full VGG model on the left: five labeled plates make the repeated organization visible. Move to the center to open one plate and expose its internal contract. End with AlexNet on the right as the reference: it uses the same broad vocabulary of convolution, pooling, and fully connected layers, but its local recipe changes by stage. The conceptual advance is architectural grammar—one reusable unit whose repetition count and channel width specify the network.</p>
</div>
</section>
<section id="the-architecture-becomes-a-short-specification" class="level2">
<h2 class="anchored" data-anchor-id="the-architecture-becomes-a-short-specification">The architecture becomes a short specification</h2>
<div class="vgg-model-code-layout">
<div class="vgg-arch-spec">
<span>PAPER CONFIGURATION A · VGG-11</span>
<pre><code>arch = ((1, 64),
        (1, 128),
        (2, 256),
        (2, 512),
        (2, 512))</code></pre>
<div class="vgg-spec-reading">
<p><b><span class="math inline">\((n, C)\)</span></b><strong>repeat <span class="math inline">\(n\)</span> convolutions<br>with <span class="math inline">\(C\)</span> output channels</strong></p>
</div>
<div class="vgg-spec-blocks">
<p><i><b>1×</b><span>64</span></i> <i><b>1×</b><span>128</span></i> <i><b>2×</b><span>256</span></i> <i><b>2×</b><span>512</span></i> <i><b>2×</b><span>512</span></i></p>
</div>
<p><small>Five tuples → five calls to <code>vgg_block</code></small></p>
</div>
<div class="light-code-editor vgg-model-editor">
<div class="editor-bar">
<span>PYTORCH · FULL MODEL</span><strong>vgg.py</strong>
</div>
<pre><code><span class="py-kw">class</span> <span class="py-fn">VGG</span>(<span class="py-mod">nn</span>.<span class="py-call">Module</span>):
    <span class="py-kw">def</span> <span class="py-fn">__init__</span>(<span class="py-param">self</span>, <span class="py-param">arch</span>, <span class="py-param">num_classes</span><span class="py-punc">=</span><span class="py-num">10</span>):
        <span class="py-call">super</span>().<span class="py-call">__init__</span>()

        conv_blocks <span class="py-punc">=</span> [
            <span class="py-call">vgg_block</span>(num_convs, out_channels)
            <span class="py-kw">for</span> num_convs, out_channels <span class="py-kw">in</span> arch
        ]

        self.net <span class="py-punc">=</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            *conv_blocks,
            <span class="py-mod">nn</span>.<span class="py-call">Flatten</span>(),
            <span class="py-mod">nn</span>.<span class="py-call">LazyLinear</span>(<span class="py-num">4096</span>), <span class="py-mod">nn</span>.<span class="py-call">ReLU</span>(), <span class="py-mod">nn</span>.<span class="py-call">Dropout</span>(<span class="py-num">0.5</span>),
            <span class="py-mod">nn</span>.<span class="py-call">LazyLinear</span>(<span class="py-num">4096</span>), <span class="py-mod">nn</span>.<span class="py-call">ReLU</span>(), <span class="py-mod">nn</span>.<span class="py-call">Dropout</span>(<span class="py-num">0.5</span>),
            <span class="py-mod">nn</span>.<span class="py-call">LazyLinear</span>(num_classes),
        )
        self.net.<span class="py-call">apply</span>(d2l.init_cnn)</code></pre>
</div>
</div>
<div class="vgg-code-trace fragment">
<p><span>TRACE THE ABSTRACTION</span><strong>configuration</strong><b>→</b><strong>block factory</strong><b>→</b><strong>feature extractor</strong><b>→</b><strong>classifier</strong></p>
</div>
<p class="source-note">
Configuration A from Table 1 of Simonyan &amp; Zisserman <span class="citation" data-cites="simonyan2015vgg">(Simonyan and Zisserman 2015)</span>. Implementation adapted from the instructor’s <a href="https://anassbelcaid.github.io/deeplearning/modernconv/">2024 course chapter</a>.
</p>
<div class="notes">
<p>Begin on the left. Each pair stores only two decisions: how many convolutions the block repeats and how many channels those convolutions produce. Configuration A expands to eight convolutional layers across five blocks; the three fully connected layers produce the name VGG-11. Then trace the list comprehension on the right: each tuple becomes one call to the block factory from the previous slide. The sequential model concatenates the five blocks, flattens once, and attaches the historical VGG classifier. Mention that num_classes is ten here for course datasets; the ImageNet paper used one thousand outputs.</p>
</div>
</section>
<section id="vggs-legacyand-its-unfinished-business" class="level2">
<h2 class="anchored" data-anchor-id="vggs-legacyand-its-unfinished-business">VGG’s legacy—and its unfinished business</h2>
<div class="network-audit-prompt">
<span>ARCHITECTURE AUDIT · VGG</span><strong>What became systematic—and what still prevents clean scaling?</strong>
</div>
<div class="network-synthesis">
<div class="network-ledger network-gains">
<span>MAIN IDEAS</span>
<div>
<b>REPEAT</b><strong>Build depth from a reusable convolutional block.</strong><small>Architecture becomes a short configuration.</small>
</div>
<div>
<b>STANDARDIZE</b><strong>Use padded <span class="math inline">\(3\times3\)</span> kernels throughout.</strong><small>Small kernels accumulate context and nonlinearities.</small>
</div>
<div>
<b>CONTROL RESOLUTION</b><strong>Pool once after several convolutions.</strong><small>Feature extraction happens before downsampling.</small>
</div>
</div>
<div class="network-ledger network-limits fragment">
<span>DRAWBACKS</span>
<div>
<b>DENSE HEAD</b><strong>Most parameters remain in the classifier.</strong><small>Flattening creates very large matrices.</small>
</div>
<div>
<b>PLAIN CHAIN</b><strong>Every signal follows one long route.</strong><small>Optimization becomes harder as depth grows.</small>
</div>
<div>
<b>COMPUTE</b><strong>Repeated dense convolutions remain expensive.</strong><small>Regular does not automatically mean efficient.</small>
</div>
</div>
</div>
<div class="network-next-step fragment">
<span>NEXT RESPONSE</span><strong>Keep spatial structure, add local channel mixing, and remove the dense head.</strong><b>→ NiN</b>
</div>
<p class="source-note">
Synthesis based on Simonyan &amp; Zisserman <span class="citation" data-cites="simonyan2015vgg">(Simonyan and Zisserman 2015)</span>.
</p>
<div class="notes">
<p>Ask students to supply one item in each column before revealing the drawbacks. VGG’s durable contribution is a regular block grammar built from small padded convolutions and deliberate pooling. Its original implementation still carries a huge fully connected classifier, and the feature extractor is a plain sequential chain. The compute cost also remains high because every block applies dense spatial convolutions. Use the final bridge to motivate NiN without claiming that NiN solves optimization at extreme depth.</p>
</div>
</section>
<section id="nin-fixes-what-vgg-leaves-expensive" class="level2">
<h2 class="anchored" data-anchor-id="nin-fixes-what-vgg-leaves-expensive">NiN fixes what VGG leaves expensive</h2>
<div class="nin-paper-line">
<p><span>LIN · CHEN · YAN · ICLR 2014</span> <strong>Network in Network</strong> <small>Replace a linear local filter with a tiny network—and remove the dense classifier.</small></p>
</div>
<div class="nin-fixes-figure">
<p><img src="assets/nin-vgg-fixes.svg" alt="Comparison of VGG's parameter-heavy fully connected classifier with NiN's local one-by-one channel mixing and global average pooling head."></p>
</div>
<div class="nin-two-fixes fragment">
<div>
<b>FIX 1 · LOCAL EXPRESSIVENESS</b><strong><span class="math inline">\(1\times1\)</span> convolutions mix channels independently at every spatial location.</strong>
</div>
<div>
<b>FIX 2 · CLASSIFIER COST</b><strong>One class map per label + global average pooling replaces the dense head.</strong>
</div>
</div>
<p class="source-note">
NiN motivation and global-average-pooling design from Lin, Chen &amp; Yan <span class="citation" data-cites="lin2014nin">(Lin et al. 2014)</span>. Framing follows the instructor’s <a href="https://anassbelcaid.github.io/deeplearning/modernconv/">2024 course chapter</a>.
</p>
<div class="notes">
<p>Start from VGG’s remaining problems, not from the NiN name. Flattening destroys the spatial arrangement and feeds a very large dense classifier. Yet inserting a standard fully connected layer earlier would also destroy spatial structure. NiN’s first move is a one-by-one convolution: at each pixel location it applies the same learned channel transformation, behaving like a shared fully connected layer without mixing locations. Its second move is global average pooling. The last block produces one spatial map per class; averaging each map yields its class logit. Ask students to point to the two places where parameters disappear.</p>
</div>
</section>
<section id="a-nin-block-learns-within-each-location" class="level2">
<h2 class="anchored" data-anchor-id="a-nin-block-learns-within-each-location">A NiN block learns within each location</h2>
<div class="nin-block-code-layout">
<div class="nin-block-figure">
<p><img src="assets/nin-block-schematic.svg" alt="A NiN block plate containing one spatial convolution and two one-by-one convolutions, each followed by ReLU."></p>
</div>
<div class="light-code-editor nin-block-editor">
<div class="editor-bar">
<span>PYTORCH · NiN BLOCK</span><strong>nin.py</strong>
</div>
<pre><code><span class="py-kw">def</span> <span class="py-fn">nin_block</span>(
    <span class="py-param">out_channels</span>, <span class="py-param">kernel_size</span>,
    <span class="py-param">stride</span><span class="py-punc">=</span><span class="py-num">1</span>, <span class="py-param">padding</span><span class="py-punc">=</span><span class="py-num">0</span>
):
    <span class="py-kw">return</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
        <span class="py-mod">nn</span>.<span class="py-call">LazyConv2d</span>(
            out_channels, kernel_size,
            stride<span class="py-punc">=</span>stride, padding<span class="py-punc">=</span>padding
        ),
        <span class="py-mod">nn</span>.<span class="py-call">ReLU</span>(),
        <span class="py-mod">nn</span>.<span class="py-call">LazyConv2d</span>(out_channels, <span class="py-num">1</span>),
        <span class="py-mod">nn</span>.<span class="py-call">ReLU</span>(),
        <span class="py-mod">nn</span>.<span class="py-call">LazyConv2d</span>(out_channels, <span class="py-num">1</span>),
        <span class="py-mod">nn</span>.<span class="py-call">ReLU</span>(),
    )</code></pre>
</div>
</div>
<div class="nin-location-contract fragment">
<p><span>AT EACH <span class="math inline">\((h,w)\)</span></span><strong>channel vector <span class="math inline">\(\mathbf{x}_{h,w}\)</span></strong><b>→</b><strong>shared MLP</strong><b>→</b><strong>richer channel vector</strong><small>Spatial positions remain distinct.</small></p>
</div>
<p class="source-note">
MLPConv block from Lin, Chen &amp; Yan <span class="citation" data-cites="lin2014nin">(Lin et al. 2014)</span>.
</p>
<div class="notes">
<p>Read the plate from bottom to top. The first convolution performs the usual spatial extraction and may change resolution. The following one-by-one convolutions do not look at neighboring pixels; they transform the channel vector at each location with shared weights. ReLU after every convolution turns the sequence into a small multilayer perceptron applied across channels. Contrast this with VGG: VGG repeats spatial three-by-three convolutions, whereas NiN follows one spatial convolution with two channel-mixing convolutions.</p>
</div>
</section>
<section id="nin-ends-with-class-mapsnot-a-dense-head" class="level2">
<h2 class="anchored" data-anchor-id="nin-ends-with-class-mapsnot-a-dense-head">NiN ends with class maps—not a dense head</h2>
<div class="nin-full-figure">
<p><img src="assets/nin-full-architecture.svg" alt="Full NiN architecture with four grouped NiN blocks, pooling after the first three, and global average pooling over class maps instead of fully connected layers."></p>
</div>
<div class="nin-head-equation fragment">
<p><span>ONE MAP PER CLASS</span><strong><span class="math inline">\(z_k = \dfrac{1}{HW}\sum_{h,w} A_{h,w,k}\)</span></strong><small>Evidence for class <span class="math inline">\(k\)</span> is averaged across all locations.</small></p>
</div>
<div class="nin-vgg-verdict fragment">
<p><strong>VGG:</strong><span>features → flatten → large dense head</span><b>→</b><strong>NiN:</strong><span>class maps → global average → logits</span></p>
</div>
<p class="source-note">
Course-made reconstruction of NiN from Lin, Chen &amp; Yan <span class="citation" data-cites="lin2014nin">(Lin et al. 2014)</span>.
</p>
<div class="notes">
<p>Build from the image upward. The first three blocks retain AlexNet-like spatial kernel sizes—eleven, five, then three—but each becomes a NiN block by adding two one-by-one transformations. Pooling follows those blocks. The final NiN block outputs num_classes channels, so each channel can be interpreted as a class evidence map. Adaptive average pooling reduces each map to one number, and flattening produces the logits. This removes the two 4096-unit fully connected layers. Emphasize the tradeoff: far fewer classifier parameters, but the model must learn spatial maps whose averages are directly predictive.</p>
</div>
</section>
<section id="the-complete-nin-module-mirrors-the-figure" class="level2">
<h2 class="anchored" data-anchor-id="the-complete-nin-module-mirrors-the-figure">The complete NiN module mirrors the figure</h2>
<div class="nin-model-code-layout">
<div class="nin-code-map">
<p><img src="assets/nin-code-map.svg" alt="Compact construction trace for the full NiN module: three feature blocks with pooling, dropout, a class-map block, global average pooling, and logits."></p>
</div>
<div class="light-code-editor nin-model-editor">
<div class="editor-bar">
<span>PYTORCH · FULL MODEL</span><strong>nin.py</strong>
</div>
<pre><code><span class="py-kw">class</span> <span class="py-fn">NiN</span>(<span class="py-mod">nn</span>.<span class="py-call">Module</span>):
    <span class="py-kw">def</span> <span class="py-fn">__init__</span>(<span class="py-param">self</span>, <span class="py-param">num_classes</span><span class="py-punc">=</span><span class="py-num">10</span>):
        <span class="py-call">super</span>().<span class="py-call">__init__</span>()

        self.net <span class="py-punc">=</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            <span class="py-call">nin_block</span>(<span class="py-num">96</span>,  <span class="py-num">11</span>, stride<span class="py-punc">=</span><span class="py-num">4</span>),
            <span class="py-mod">nn</span>.<span class="py-call">MaxPool2d</span>(<span class="py-num">3</span>, stride<span class="py-punc">=</span><span class="py-num">2</span>),
            <span class="py-call">nin_block</span>(<span class="py-num">256</span>, <span class="py-num">5</span>, padding<span class="py-punc">=</span><span class="py-num">2</span>),
            <span class="py-mod">nn</span>.<span class="py-call">MaxPool2d</span>(<span class="py-num">3</span>, stride<span class="py-punc">=</span><span class="py-num">2</span>),
            <span class="py-call">nin_block</span>(<span class="py-num">384</span>, <span class="py-num">3</span>, padding<span class="py-punc">=</span><span class="py-num">1</span>),
            <span class="py-mod">nn</span>.<span class="py-call">MaxPool2d</span>(<span class="py-num">3</span>, stride<span class="py-punc">=</span><span class="py-num">2</span>),
            <span class="py-mod">nn</span>.<span class="py-call">Dropout</span>(<span class="py-num">0.5</span>),
            <span class="py-call">nin_block</span>(num_classes, <span class="py-num">3</span>, padding<span class="py-punc">=</span><span class="py-num">1</span>),
            <span class="py-mod">nn</span>.<span class="py-call">AdaptiveAvgPool2d</span>((<span class="py-num">1</span>, <span class="py-num">1</span>)),
            <span class="py-mod">nn</span>.<span class="py-call">Flatten</span>(),
        )
        self.net.<span class="py-call">apply</span>(d2l.init_cnn)</code></pre>
</div>
</div>
<div class="nin-model-trace fragment">
<p><span>LAST THREE LINES</span><strong><span class="math inline">\(K\)</span> class maps</strong><b>→</b><strong>average each map to <span class="math inline">\(1\times1\)</span></strong><b>→</b><strong>flatten to <span class="math inline">\(K\)</span> logits</strong></p>
</div>
<p class="source-note">
Implementation adapted from the instructor’s <a href="https://anassbelcaid.github.io/deeplearning/modernconv/">2024 course chapter</a> and Lin, Chen &amp; Yan <span class="citation" data-cites="lin2014nin">(Lin et al. 2014)</span>.
</p>
<div class="notes">
<p>Map each code line to the compact trace. The first three NiN blocks use the same spatial kernel sizes and output channels described on the previous slide, with max pooling after each block. Dropout regularizes the final feature representation. The last NiN block has num_classes output channels, producing one evidence map per class. AdaptiveAvgPool2d forces every map to one-by-one regardless of the incoming spatial size, and Flatten converts the K scalar averages into the classifier output. We omit the learning-rate argument and save_hyperparameters because this class is a plain torch module; training configuration belongs outside the architecture.</p>
</div>
</section>
<section id="nin-changes-both-the-block-and-the-head" class="level2">
<h2 class="anchored" data-anchor-id="nin-changes-both-the-block-and-the-head">NiN changes both the block and the head</h2>
<div class="network-audit-prompt">
<span>ARCHITECTURE AUDIT · NiN</span><strong>Which VGG costs disappear—and which design choices remain rigid?</strong>
</div>
<div class="network-synthesis">
<div class="network-ledger network-gains">
<span>MAIN IDEAS</span>
<div>
<b>LOCAL MLP</b><strong>Stack <span class="math inline">\(1\times1\)</span> convolutions inside each block.</strong><small>Mix channels without destroying spatial layout.</small>
</div>
<div>
<b>CLASS MAPS</b><strong>Produce one spatial evidence map per class.</strong><small>The representation connects directly to prediction.</small>
</div>
<div>
<b>GLOBAL AVERAGE</b><strong>Replace the dense classifier with averaging.</strong><small>Classifier parameters collapse dramatically.</small>
</div>
</div>
<div class="network-ledger network-limits fragment">
<span>DRAWBACKS</span>
<div>
<b>FIXED PATH</b><strong>Every block still chooses one spatial kernel.</strong><small>Only one receptive-field scale is processed at a time.</small>
</div>
<div>
<b>AGGRESSIVE STEM</b><strong>Large early kernels and pooling remain.</strong><small>Fine spatial evidence can disappear quickly.</small>
</div>
<div>
<b>CLASS-MAP CONTRACT</b><strong>The last channels must become class evidence.</strong><small>Global averaging can discard spatial arrangement.</small>
</div>
</div>
</div>
<div class="network-next-step fragment">
<span>NEXT RESPONSE</span><strong>Process several spatial scales in parallel, then concatenate their evidence.</strong><b>→ Inception</b>
</div>
<p class="source-note">
Synthesis based on Lin, Chen &amp; Yan <span class="citation" data-cites="lin2014nin">(Lin et al. 2014)</span>.
</p>
<div class="notes">
<p>Retrieve the two NiN fixes first: local channel-wise nonlinear transformations and a parameter-light global-average-pooling head. Then ask what NiN still forces the designer to choose. Each spatial stage selects one kernel size and follows one path. Its early architecture also retains AlexNet-like wide kernels and aggressive pooling. The final class-map contract is elegant but restrictive: the representation must align channels with labels before averaging. This leads naturally to Inception’s parallel multi-scale paths.</p>
</div>
</section>
</section>
<section id="branching-across-spatial-scales-1" class="level1 section-slide architecture-section branching-section" data-section-progress="3 / 7" style="--section-progress:42.857%">
<h1 class="section-slide architecture-section branching-section" data-section-progress="3 / 7" style="--section-progress:42.857%">03 · Branching across spatial scales</h1>
<section id="one-inputfour-receptive-field-choices" class="level2">
<h2 class="anchored" data-anchor-id="one-inputfour-receptive-field-choices">One input—four receptive-field choices</h2>
<div class="inception-paper-line">
<p><span>SZEGEDY ET AL. · CVPR 2015</span><strong>Going Deeper with Convolutions</strong><small>Instead of choosing one kernel size, let the block learn from several scales in parallel.</small></p>
</div>
<div class="inception-block-figure">
<p><img src="assets/inception-block-schematic.svg" alt="An Inception block splitting one input into four branches using one-by-one, three-by-three, five-by-five, and pooling operations, then concatenating their outputs along channels."></p>
</div>
<div class="inception-reading fragment">
<span>SAME <span class="math inline">\(H\times W\)</span></span><strong>Every path preserves spatial size.</strong><b>+</b><span>DIFFERENT EVIDENCE</span><strong>Each path sees or summarizes a different spatial extent.</strong><b>→</b><span>CONCATENATE</span><strong>Keep every branch along the channel axis.</strong>
</div>
<p class="source-note">
Course-made Inception diagram based on Szegedy et al. <span class="citation" data-cites="szegedy2015googlenet">(Szegedy et al. 2015)</span>.
</p>
<div class="notes">
<p>Ask students to choose a kernel size before revealing the full diagram. The Inception answer is not to choose: the input is sent through four parallel paths. The one-by-one branch captures channel interactions, the three-by-three and five-by-five branches see different spatial extents, and the pooling branch summarizes local context. All branches preserve height and width through stride one and appropriate padding, which makes concatenation possible. Concatenation increases channels; it does not add the branch tensors elementwise.</p>
</div>
</section>
<section id="the-1times1-layers-are-capacity-valves" class="level2">
<h2 class="anchored" data-anchor-id="the-1times1-layers-are-capacity-valves">The <span class="math inline">\(1\times1\)</span> layers are capacity valves</h2>
<div class="inception-bottleneck-layout">
<div class="inception-expensive-path">
<span>WITHOUT REDUCTION</span><strong><span class="math inline">\(C_{in}\xrightarrow{5\times5}C_{out}\)</span></strong>
<div>
<b><span class="math inline">\(25C_{in}C_{out}\)</span></b><small>weights</small>
</div>
</div>
<div class="inception-valve-path fragment">
<span>WITH A <span class="math inline">\(1\times1\)</span> VALVE</span><strong><span class="math inline">\(C_{in}\xrightarrow{1\times1}C_r\xrightarrow{5\times5}C_{out}\)</span></strong>
<div>
<b><span class="math inline">\(C_{in}C_r+25C_rC_{out}\)</span></b><small>weights</small>
</div>
</div>
</div>
<div class="inception-capacity-choice fragment">
<span>THE DESIGN VARIABLE</span><strong>Allocate channels to branches—not one kernel to the entire layer.</strong><small>The reduction width <span class="math inline">\(C_r\)</span> controls how expensive the wider spatial kernel becomes.</small>
</div>
<p class="source-note">
Dimension-reduction rationale from Szegedy et al. <span class="citation" data-cites="szegedy2015googlenet">(Szegedy et al. 2015)</span>.
</p>
<div class="notes">
<p>Use the five-by-five branch to explain why the one-by-one convolution appears before wider kernels. A direct five-by-five convolution costs twenty-five times input channels times output channels. Reducing first to Cr channels changes the cost to Cin times Cr plus twenty-five times Cr times Cout. The one-by-one layer is therefore a learned capacity valve. It also adds a nonlinearity. Ask students what happens as Cr approaches Cin: the saving disappears.</p>
</div>
</section>
<section id="the-diagram-becomes-an-inception-module" class="level2">
<h2 class="anchored" data-anchor-id="the-diagram-becomes-an-inception-module">The diagram becomes an Inception module</h2>
<div class="inception-code-layout">
<div class="inception-code-miniature">
<p><img src="assets/inception-block-schematic.svg" alt="Compact Inception block diagram corresponding to the four branches in the adjacent PyTorch implementation."></p>
</div>
<div class="light-code-editor inception-editor">
<div class="editor-bar">
<span>PYTORCH · FOUR BRANCHES</span><strong>inception.py</strong>
</div>
<pre><code><span class="py-kw">class</span> <span class="py-fn">Inception</span>(<span class="py-mod">nn</span>.<span class="py-call">Module</span>):
    <span class="py-kw">def</span> <span class="py-fn">__init__</span>(<span class="py-param">self</span>, <span class="py-param">c1</span>, <span class="py-param">c2</span>, <span class="py-param">c3</span>, <span class="py-param">c4</span>):
        <span class="py-call">super</span>().<span class="py-call">__init__</span>()
        self.b1 <span class="py-punc">=</span> conv_relu(c1, <span class="py-num">1</span>)
        self.b2 <span class="py-punc">=</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            conv_relu(c2[<span class="py-num">0</span>], <span class="py-num">1</span>),
            conv_relu(c2[<span class="py-num">1</span>], <span class="py-num">3</span>, padding<span class="py-punc">=</span><span class="py-num">1</span>))
        self.b3 <span class="py-punc">=</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            conv_relu(c3[<span class="py-num">0</span>], <span class="py-num">1</span>),
            conv_relu(c3[<span class="py-num">1</span>], <span class="py-num">5</span>, padding<span class="py-punc">=</span><span class="py-num">2</span>))
        self.b4 <span class="py-punc">=</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            <span class="py-mod">nn</span>.<span class="py-call">MaxPool2d</span>(<span class="py-num">3</span>, stride<span class="py-punc">=</span><span class="py-num">1</span>, padding<span class="py-punc">=</span><span class="py-num">1</span>),
            conv_relu(c4, <span class="py-num">1</span>))

    <span class="py-kw">def</span> <span class="py-fn">forward</span>(<span class="py-param">self</span>, <span class="py-param">x</span>):
        ys <span class="py-punc">=</span> [branch(x) <span class="py-kw">for</span> branch <span class="py-kw">in</span>
              (self.b1, self.b2, self.b3, self.b4)]
        <span class="py-kw">return</span> <span class="py-mod">torch</span>.<span class="py-call">cat</span>(ys, dim<span class="py-punc">=</span><span class="py-num">1</span>)</code></pre>
</div>
</div>
<div class="inception-code-contract fragment">
<span>SHAPE CONTRACT</span><strong>branches agree on <span class="math inline">\((H,W)\)</span></strong><b>→</b><strong><code>torch.cat(…, dim=1)</code></strong><b>→</b><strong>channels sum</strong>
</div>
<p class="source-note">
Simplified PyTorch implementation based on Szegedy et al. <span class="citation" data-cites="szegedy2015googlenet">(Szegedy et al. 2015)</span> and the instructor’s <a href="https://anassbelcaid.github.io/deeplearning/modernconv/">2024 course chapter</a>.
</p>
<div class="notes">
<p>The helper conv_relu denotes a convolution followed by ReLU and keeps the code focused on branch topology. Match b1 through b4 to the four lanes in the figure. Each branch receives the same x. Because padding preserves height and width, torch.cat can join the outputs along dimension one, the channel dimension in NCHW tensors. Ask students to compute the output channel count: c1 plus c2[1] plus c3[1] plus c4.</p>
</div>
</section>
<section id="once-understood-compress-the-block" class="level2">
<h2 class="anchored" data-anchor-id="once-understood-compress-the-block">Once understood, compress the block</h2>
<div class="googlenet-compressed-figure">
<img src="assets/googlenet-compressed.svg" alt="GoogLeNet architecture assembled from nine compressed Inception block symbols arranged into groups of two, five, and two, with pooling between groups and global average pooling in the head.">
</div>
<div class="googlenet-reading fragment">
<span>STEM</span><strong>ingest the image</strong><b>→</b><span>BODY</span><strong>2 + 5 + 2 Inception blocks</strong><b>→</b><span>HEAD</span><strong>global average pooling + classifier</strong>
</div>
<p class="source-note">
Course-made compressed GoogLeNet diagram based on Szegedy et al. <span class="citation" data-cites="szegedy2015googlenet">(Szegedy et al. 2015)</span>. The original network also used auxiliary classifiers during training.
</p>
<div class="notes">
<p>Now that students understand the internal four-branch structure, replace it with one compact green symbol. GoogLeNet uses nine Inception blocks arranged into groups of two, five, and two, with max pooling between groups. The stem performs early image ingestion; the body performs multi-scale processing; the head uses global average pooling, inherited conceptually from NiN, before classification. Mention that the original paper included auxiliary classifiers to stabilize training, but the simplified course implementation omits them because modern training recipes make them less essential.</p>
</div>
</section>
<section id="nine-blocks-become-one-googlenet-class" class="level2">
<h2 class="anchored" data-anchor-id="nine-blocks-become-one-googlenet-class">Nine blocks become one GoogLeNet class</h2>
<div class="googlenet-code-layout">
<div class="googlenet-code-map">
<div class="gg-mini-head">
GAP → Linear(K)
</div>
<div class="gg-mini-stage">
<span>BODY 5</span><strong>Inception × 2</strong>
</div>
<b>↑</b>
<div class="gg-mini-pool">
MaxPool · stride 2
</div>
<div class="gg-mini-stage five-stage">
<span>BODY 4</span><strong>Inception × 5</strong>
</div>
<b>↑</b>
<div class="gg-mini-pool">
MaxPool · stride 2
</div>
<div class="gg-mini-stage">
<span>BODY 3</span><strong>Inception × 2</strong>
</div>
<b>↑</b>
<div class="gg-mini-stem">
STEM
</div>
<div class="gg-mini-input">
224² × 3 image
</div>
</div>
<div class="light-code-editor googlenet-editor">
<div class="editor-bar">
<span>PYTORCH · COMPRESSED MODEL</span><strong>googlenet.py</strong>
</div>
<pre><code><span class="py-kw">class</span> <span class="py-fn">GoogLeNet</span>(<span class="py-mod">nn</span>.<span class="py-call">Module</span>):
    <span class="py-kw">def</span> <span class="py-fn">__init__</span>(<span class="py-param">self</span>, <span class="py-param">num_classes</span><span class="py-punc">=</span><span class="py-num">10</span>):
        <span class="py-call">super</span>().<span class="py-call">__init__</span>()
        pool <span class="py-punc">=</span> <span class="py-kw">lambda</span>: <span class="py-mod">nn</span>.<span class="py-call">MaxPool2d</span>(<span class="py-num">3</span>, <span class="py-num">2</span>, <span class="py-num">1</span>)

        self.stem <span class="py-punc">=</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            conv_relu(<span class="py-num">64</span>, <span class="py-num">7</span>, stride<span class="py-punc">=</span><span class="py-num">2</span>, padding<span class="py-punc">=</span><span class="py-num">3</span>), pool(),
            conv_relu(<span class="py-num">64</span>, <span class="py-num">1</span>), conv_relu(<span class="py-num">192</span>, <span class="py-num">3</span>, padding<span class="py-punc">=</span><span class="py-num">1</span>), pool())

        self.body <span class="py-punc">=</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            Inception(<span class="py-num">64</span>, (<span class="py-num">96</span>,<span class="py-num">128</span>), (<span class="py-num">16</span>,<span class="py-num">32</span>), <span class="py-num">32</span>),
            Inception(<span class="py-num">128</span>, (<span class="py-num">128</span>,<span class="py-num">192</span>), (<span class="py-num">32</span>,<span class="py-num">96</span>), <span class="py-num">64</span>), pool(),
            Inception(<span class="py-num">192</span>, (<span class="py-num">96</span>,<span class="py-num">208</span>), (<span class="py-num">16</span>,<span class="py-num">48</span>), <span class="py-num">64</span>),
            Inception(<span class="py-num">160</span>, (<span class="py-num">112</span>,<span class="py-num">224</span>), (<span class="py-num">24</span>,<span class="py-num">64</span>), <span class="py-num">64</span>),
            Inception(<span class="py-num">128</span>, (<span class="py-num">128</span>,<span class="py-num">256</span>), (<span class="py-num">24</span>,<span class="py-num">64</span>), <span class="py-num">64</span>),
            Inception(<span class="py-num">112</span>, (<span class="py-num">144</span>,<span class="py-num">288</span>), (<span class="py-num">32</span>,<span class="py-num">64</span>), <span class="py-num">64</span>),
            Inception(<span class="py-num">256</span>, (<span class="py-num">160</span>,<span class="py-num">320</span>), (<span class="py-num">32</span>,<span class="py-num">128</span>), <span class="py-num">128</span>), pool(),
            Inception(<span class="py-num">256</span>, (<span class="py-num">160</span>,<span class="py-num">320</span>), (<span class="py-num">32</span>,<span class="py-num">128</span>), <span class="py-num">128</span>),
            Inception(<span class="py-num">384</span>, (<span class="py-num">192</span>,<span class="py-num">384</span>), (<span class="py-num">48</span>,<span class="py-num">128</span>), <span class="py-num">128</span>))

        self.head <span class="py-punc">=</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            <span class="py-mod">nn</span>.<span class="py-call">AdaptiveAvgPool2d</span>((<span class="py-num">1</span>,<span class="py-num">1</span>)), <span class="py-mod">nn</span>.<span class="py-call">Flatten</span>(),
            <span class="py-mod">nn</span>.<span class="py-call">Dropout</span>(<span class="py-num">0.4</span>), <span class="py-mod">nn</span>.<span class="py-call">LazyLinear</span>(num_classes))

    <span class="py-kw">def</span> <span class="py-fn">forward</span>(<span class="py-param">self</span>, <span class="py-param">x</span>):
        <span class="py-kw">return</span> self.head(self.body(self.stem(x)))</code></pre>
</div>
</div>
<div class="googlenet-code-trace fragment">
<span>READ THE CLASS</span><strong><code>stem</code></strong><b>→</b><strong><code>body</code>: 2 + 5 + 2 blocks</strong><b>→</b><strong><code>head</code>: GAP + classifier</strong>
</div>
<p class="source-note">
Simplified GoogLeNet without auxiliary classifiers, based on Szegedy et al. <span class="citation" data-cites="szegedy2015googlenet">(Szegedy et al. 2015)</span>.
</p>
<div class="notes">
<p>Keep the compressed figure visible while reading the class. The stem performs early downsampling and reaches 192 channels. The body contains exactly nine Inception calls: two before the first pool, five before the second, and two at the final resolution. Each constructor tuple allocates output channels across the four branches. The head compresses each channel to one spatial value, flattens, applies dropout, and learns the final class projection. The forward method exposes the persistent stem–body–head pattern. This simplified teaching implementation omits the original auxiliary classifiers.</p>
</div>
</section>
<section id="googlenet-gains-scale-diversityat-a-cost" class="level2">
<h2 class="anchored" data-anchor-id="googlenet-gains-scale-diversityat-a-cost">GoogLeNet gains scale diversity—at a cost</h2>
<div class="network-audit-prompt">
<span>ARCHITECTURE AUDIT · GOOGLENET</span><strong>What does branching buy—and what complexity does it introduce?</strong>
</div>
<div class="network-synthesis">
<div class="network-ledger network-gains">
<span>MAIN IDEAS</span>
<div>
<b>MULTI-SCALE</b><strong>Process <span class="math inline">\(1\times1\)</span>, <span class="math inline">\(3\times3\)</span>, <span class="math inline">\(5\times5\)</span>, and pooled evidence together.</strong><small>The block avoids committing to one receptive field.</small>
</div>
<div>
<b>CAPACITY VALVES</b><strong>Use <span class="math inline">\(1\times1\)</span> reductions before wide kernels.</strong><small>Branch widths allocate the parameter budget.</small>
</div>
<div>
<b>MODULAR BODY</b><strong>Compress four paths into one reusable symbol.</strong><small>Nine blocks form a clear stem–body–head network.</small>
</div>
</div>
<div class="network-ledger network-limits fragment">
<span>DRAWBACKS</span>
<div>
<b>HAND-TUNED WIDTHS</b><strong>Every branch needs several channel choices.</strong><small>The architecture specification becomes intricate.</small>
</div>
<div>
<b>BRANCH COMPLEXITY</b><strong>Parallel paths complicate implementation and hardware scheduling.</strong><small>Fewer parameters do not guarantee simple execution.</small>
</div>
<div>
<b>TRAINING SUPPORT</b><strong>The original model used auxiliary classifiers.</strong><small>Very deep plain information paths remain difficult.</small>
</div>
</div>
</div>
<div class="network-next-step fragment">
<span>OPEN PROBLEM</span><strong>Can adding depth preserve an easy route for information and gradients?</strong><b>→ residual learning</b>
</div>
<p class="source-note">
Synthesis based on Szegedy et al. <span class="citation" data-cites="szegedy2015googlenet">(Szegedy et al. 2015)</span>.
</p>
<div class="notes">
<p>Have students name the benefit of each branch before showing the drawbacks. GoogLeNet makes multi-scale processing explicit and uses one-by-one reductions to allocate capacity economically. Once compressed, the Inception symbol supports a modular nine-block body. The cost is architectural complexity: many branch widths must be hand tuned, parallel paths are less straightforward to schedule, and the original model used auxiliary classifiers during training. Close on the remaining information-flow problem, which prepares the residual-learning section without teaching it yet.</p>
</div>
</section>
</section>
<section id="learning-residual-corrections-1" class="level1 section-slide architecture-section resnet-section" data-section-progress="4 / 7" style="--section-progress:57.143%">
<h1 class="section-slide architecture-section resnet-section" data-section-progress="4 / 7" style="--section-progress:57.143%">04 · Learning residual corrections</h1>
<div class="resnet-evidence-layout">
<div class="resnet-paper-figure">
<p><img src="assets/resnet-plain-degradation-figure1.png" alt="Training and test error curves from the ResNet paper comparing plain 20-layer and 56-layer networks on CIFAR-10; the deeper plain network has higher error."> <small>Plain networks on CIFAR-10 · He et al., Figure 1</small></p>
</div>
<div class="resnet-evidence-question">
<span>PREDICT BEFORE REVEAL</span> <strong>If 20 layers work, should 56 layers fit the training set at least as well?</strong>
<div class="fragment">
<b>No.</b>
<p>
The deeper <em>plain</em> network has higher training error—not merely higher test error.
</p>
</div>
<div class="fragment">
<b>DIAGNOSIS</b>
<p>
Extra depth created an optimization problem: the added layers failed even to learn an identity mapping.
</p>
</div>
</div>
</div>
<p class="source-note">
Original experimental curves reproduced from He et al. <span class="citation" data-cites="he2016resnet">(He et al. 2016)</span>, Figure 1.
</p>
<div class="notes">
<p>Begin with the apparently obvious claim: a deeper model contains enough capacity to imitate the shallower one by making the extra layers identities. Ask students to predict the 56-layer training curve. Reveal that it is worse than the 20-layer curve. Because the failure already appears in training error, this is not the usual overfitting story. He et al.&nbsp;call it the degradation problem. The architecture needs to make “do nothing” easy before depth can become reliably useful.</p>
</div>
<section id="learn-the-correctionnot-the-whole-transformation" class="level2">
<h2 class="anchored" data-anchor-id="learn-the-correctionnot-the-whole-transformation">Learn the correction—not the whole transformation</h2>
<div class="residual-mechanism-layout">
<div class="residual-main-figure">
<img src="assets/residual-block-schematic.svg" alt="Residual block in which an identity shortcut carries x around two convolutions and addition produces F(x) plus x.">
</div>
<div class="residual-idea-stack">
<span>THE RESIDUAL CONTRACT</span>
<div class="fragment">
<b>TARGET</b><strong>Desired mapping: <span class="math inline">\(H(x)\)</span></strong><small>A plain stack must learn the entire transformation.</small>
</div>
<div class="fragment">
<b>REPARAMETERIZE</b><strong>Learn <span class="math inline">\(F(x)=H(x)-x\)</span></strong><small>The block returns <span class="math inline">\(H(x)=F(x)+x\)</span>.</small>
</div>
<div class="fragment">
<b>EASY FALLBACK</b><strong>Set <span class="math inline">\(F(x)\approx0\)</span> to preserve <span class="math inline">\(x\)</span></strong><small>Information and gradients retain a direct route.</small>
</div>
</div>
</div>
<div class="residual-verdict fragment">
<span>ASK THE ROOM</span><strong>What must be true before the two paths can be added?</strong><b>same shape</b>
</div>
<p class="source-note">
Course-made diagram based on the residual building block in He et al. <span class="citation" data-cites="he2016resnet">(He et al. 2016)</span>.
</p>
<div class="notes">
<p>Trace the two routes with a finger. The main path learns a correction F(x); the shortcut transports x unchanged. Addition is elementwise, so shape compatibility is a hard interface contract. Ask what happens if all convolutional weights produce zero: the block becomes an identity after the final activation. The important claim is not that gradients magically avoid every difficulty, but that residual parameterization provides a short information and gradient route and makes the identity solution accessible.</p>
</div>
</section>
<section id="one-block-two-shortcut-policies" class="level2">
<h2 class="anchored" data-anchor-id="one-block-two-shortcut-policies">One block, two shortcut policies</h2>
<div class="residual-code-layout">
<div class="residual-code-visual">
<span>READ THE DECISION</span>
<div class="res-code-choice">
<b>same shape?</b><strong><code>projection = None</code></strong><small>Reuse <span class="math inline">\(x\)</span> directly.</small>
</div>
<div class="res-code-arrow">
↓
</div>
<div class="res-code-choice projected">
<b>shape changes?</b><strong><code>Conv2d(1×1)</code></strong><small>Align channels and resolution.</small>
</div>
<div class="res-code-sum">
<strong><span class="math inline">\(F(x)\)</span></strong><b>+</b><strong><span class="math inline">\(x\)</span> or <span class="math inline">\(W_sx\)</span></strong>
</div>
</div>
<div class="light-code-editor residual-editor">
<div class="editor-bar">
<span>PYTORCH · RESIDUAL BLOCK</span><strong>residual.py</strong>
</div>
<pre><code><span class="py-kw">class</span> <span class="py-fn">ResidualBlock</span>(<span class="py-mod">nn</span>.<span class="py-call">Module</span>):
    <span class="py-kw">def</span> <span class="py-fn">__init__</span>(<span class="py-self">self</span>, in_ch, out_ch,
                 stride=<span class="py-num">1</span>, use_projection=<span class="py-bool">False</span>):
        <span class="py-mod">super</span>().<span class="py-call">__init__</span>()
        <span class="py-self">self</span>.main = <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            <span class="py-mod">nn</span>.<span class="py-call">Conv2d</span>(in_ch, out_ch, <span class="py-num">3</span>, stride,
                      padding=<span class="py-num">1</span>, bias=<span class="py-bool">False</span>),
            <span class="py-mod">nn</span>.<span class="py-call">BatchNorm2d</span>(out_ch), <span class="py-mod">nn</span>.<span class="py-call">ReLU</span>(),
            <span class="py-mod">nn</span>.<span class="py-call">Conv2d</span>(out_ch, out_ch, <span class="py-num">3</span>,
                      padding=<span class="py-num">1</span>, bias=<span class="py-bool">False</span>),
            <span class="py-mod">nn</span>.<span class="py-call">BatchNorm2d</span>(out_ch))

        <span class="py-self">self</span>.shortcut = (
            <span class="py-mod">nn</span>.<span class="py-call">Conv2d</span>(in_ch, out_ch, <span class="py-num">1</span>, stride,
                      bias=<span class="py-bool">False</span>)
            <span class="py-kw">if</span> use_projection <span class="py-kw">else</span> <span class="py-bool">None</span>)

    <span class="py-kw">def</span> <span class="py-fn">forward</span>(<span class="py-self">self</span>, x):
        identity = x <span class="py-kw">if</span> <span class="py-self">self</span>.shortcut <span class="py-kw">is</span> <span class="py-bool">None</span> \
                     <span class="py-kw">else</span> <span class="py-self">self</span>.shortcut(x)
        <span class="py-kw">return</span> <span class="py-mod">F</span>.<span class="py-call">relu</span>(<span class="py-self">self</span>.main(x) + identity)</code></pre>
</div>
</div>
<p class="source-note">
Teaching implementation of the basic residual block from He et al. <span class="citation" data-cites="he2016resnet">(He et al. 2016)</span>.
</p>
<div class="notes">
<p>Keep the code as the principal content. The main branch is identical in both cases; only the shortcut policy changes. With stride one and equal channel counts, use_projection stays false and identity is exactly x. At a stage boundary, the caller sets stride two and enables the one-by-one projection. Point out that both paths then downsample consistently before addition. This explicit flag makes the architectural decision visible to students.</p>
</div>
</section>
<section id="addition-imposes-a-shape-contract" class="level2">
<h2 class="anchored" data-anchor-id="addition-imposes-a-shape-contract">Addition imposes a shape contract</h2>
<div class="residual-variants-figure">
<img src="assets/residual-shortcut-variants.svg" alt="Side-by-side residual blocks: an identity shortcut for matching shapes and a one-by-one convolutional projection for changing spatial size and channels.">
</div>
<div class="residual-shape-contract">
<div>
<span>IDENTITY</span><strong><code>ResidualBlock(64, 64)</code></strong><small>H × W × C stays fixed · zero shortcut parameters</small>
</div>
<div>
<span>PROJECTION</span><strong><code>ResidualBlock(64, 128, stride=2, use_projection=True)</code></strong><small>H and W halve · channels double · learned alignment</small>
</div>
</div>
<div class="residual-takeaway fragment">
<span>DESIGN RULE</span><strong>Use identity whenever shapes agree; project only when the stage changes shape.</strong>
</div>
<p class="source-note">
Course-made comparison based on the shortcut options in He et al. <span class="citation" data-cites="he2016resnet">(He et al. 2016)</span>.
</p>
<div class="notes">
<p>Ask students to decide which shortcut the two constructor calls require before revealing the design rule. Addition requires identical H, W, and C. Inside a stage, the residual branch preserves shape and the free identity shortcut is preferable. At a stage transition, stride two changes spatial resolution and the output channel count grows, so a one-by-one convolution applies the same stride and learns the necessary channel projection. Contrast this with concatenation: addition preserves the channel count rather than stacking both representations.</p>
</div>
</section>
</section>
<section id="reusing-every-feature-with-densenet" class="level1 section-slide architecture-section densenet-section" data-section-progress="5 / 7" style="--section-progress:71.429%">
<h1 class="section-slide architecture-section densenet-section" data-section-progress="5 / 7" style="--section-progress:71.429%">05 · Reusing every feature with DenseNet</h1>
<div class="densenet-paper-layout">
<div class="densenet-paper-figure">
<img src="assets/densenet-paper-figure1.png" alt="Figure 1 from the DenseNet paper showing a five-layer dense block in which each layer receives all earlier feature maps.">
</div>
<div class="densenet-paper-question">
<span>READ THE CONNECTIONS</span> <strong>What reaches <span class="math inline">\(H_4\)</span> that would not reach it in a plain chain?</strong>
<div class="fragment">
<b>EVERY EARLIER FEATURE</b>
<p>
<span class="math inline">\(H_4\)</span> receives <span class="math inline">\([x_0,x_1,x_2,x_3]\)</span> directly.
</p>
</div>
<div class="fragment">
<b>NO SUMMATION</b>
<p>
Features remain distinguishable because DenseNet concatenates them.
</p>
</div>
<p><a href="https://arxiv.org/abs/1608.06993" target="_blank" rel="noopener">Read the original paper ↗</a></p>
</div>
</div>
<p class="source-note">
Original Figure 1 from Huang et al. <span class="citation" data-cites="huang2017densenet">(Huang et al. 2017)</span>. <a href="https://arxiv.org/abs/1608.06993">Densely Connected Convolutional Networks</a>.
</p>
<div class="notes">
<p>Let students inspect the colored curves before naming the mechanism. Ask them to list the inputs of H4. A plain chain would supply only x3; the dense block supplies x0 through x3. The paper’s figure uses growth rate k=4: each layer contributes only four new feature maps, but all earlier maps remain available. Make the paper link explicit so students can trace the architecture to its primary source.</p>
</div>
<section id="a-dense-layer-appendsit-does-not-replace" class="level2">
<h2 class="anchored" data-anchor-id="a-dense-layer-appendsit-does-not-replace">A dense layer appends—it does not replace</h2>
<div class="dense-mechanism-layout">
<div class="dense-main-figure">
<img src="assets/densenet-reuse-schematic.svg" alt="Course diagram of four dense layers receiving all previous features and appending k channels each.">
</div>
<div class="dense-idea-stack">
<span>THE DENSE CONTRACT</span>
<div class="fragment">
<b>READ</b><strong><span class="math inline">\(z_\ell=[x_0,\ldots,x_{\ell-1}]\)</span></strong><small>Concatenate the entire feature history.</small>
</div>
<div class="fragment">
<b>CONTRIBUTE</b><strong><span class="math inline">\(x_\ell=H_\ell(z_\ell)\)</span></strong><small>Produce only <span class="math inline">\(k\)</span> new feature maps.</small>
</div>
<div class="fragment">
<b>GROW</b><strong><span class="math inline">\(C_\ell=C_0+\ell k\)</span></strong><small>The growth rate controls new capacity.</small>
</div>
</div>
</div>
<div class="dense-resnet-contrast fragment">
<span>RESNET</span><strong><span class="math inline">\(F(x)+x\)</span> · combine by addition</strong><b>vs.</b><span>DENSENET</span><strong><span class="math inline">\([x_0,x_1,\ldots]\)</span> · preserve by concatenation</strong>
</div>
<p class="source-note">
Course-made diagram based on Huang et al. <span class="citation" data-cites="huang2017densenet">(Huang et al. 2017)</span>.
</p>
<div class="notes">
<p>Build the equations from the picture rather than presenting them first. Each layer reads the concatenated feature history and contributes k new maps. The channel count therefore grows linearly within a dense block. Contrast this with ResNet’s addition: ResNet merges two same-shaped tensors into one state, whereas DenseNet preserves separate feature maps and makes them jointly visible downstream.</p>
</div>
</section>
<section id="watch-the-feature-bank-grow" class="level2">
<h2 class="anchored" data-anchor-id="watch-the-feature-bank-grow">Watch the feature bank grow</h2>
<div class="dense-growth-question">
<span>START WITH</span><strong><span class="math inline">\(C_0=8\)</span> channels</strong><span>EACH LAYER ADDS</span><strong><span class="math inline">\(k=4\)</span> channels</strong><b>Predict the width after four layers.</b>
</div>
<div class="dense-growth-animation">
<div class="growth-stage">
<span>INPUT</span>
<div class="dense-channel-bank">
<i></i><i></i>
</div>
<strong>8</strong><small>channels</small>
</div>
<b class="fragment">+</b>
<div class="growth-stage fragment">
<span><span class="math inline">\(H_1\)</span> ADDS 4</span>
<div class="dense-channel-bank">
<i></i><i></i><i></i>
</div>
<strong>12</strong><small><span class="math inline">\(8+4\)</span></small>
</div>
<b class="fragment">+</b>
<div class="growth-stage fragment">
<span><span class="math inline">\(H_2\)</span> ADDS 4</span>
<div class="dense-channel-bank">
<i></i><i></i><i></i><i></i>
</div>
<strong>16</strong><small><span class="math inline">\(8+2(4)\)</span></small>
</div>
<b class="fragment">+</b>
<div class="growth-stage fragment">
<span><span class="math inline">\(H_3\)</span> ADDS 4</span>
<div class="dense-channel-bank">
<i></i><i></i><i></i><i></i><i></i>
</div>
<strong>20</strong><small><span class="math inline">\(8+3(4)\)</span></small>
</div>
<b class="fragment">+</b>
<div class="growth-stage fragment">
<span><span class="math inline">\(H_4\)</span> ADDS 4</span>
<div class="dense-channel-bank">
<i></i><i></i><i></i><i></i><i></i><i></i>
</div>
<strong>24</strong><small><span class="math inline">\(8+4(4)\)</span></small>
</div>
</div>
<div class="dense-growth-rule fragment">
<span>GENERAL RULE</span><strong>After <span class="math inline">\(L\)</span> layers: <span class="math inline">\(C_L=C_0+Lk\)</span></strong><b>Depth grows the feature bank predictably.</b>
</div>
<div class="notes">
<p>Ask for the final width before advancing. Reveal one dense layer at a time and make students update the running channel count aloud. The key is that a layer does not output the entire wider state from scratch: it computes only k new maps, then concatenation carries the existing bank forward. With C0 equal to eight, growth rate four, and four layers, the output contains twenty-four channels.</p>
</div>
</section>
<section id="cool-the-representation-before-it-grows-again" class="level2">
<h2 class="anchored" data-anchor-id="cool-the-representation-before-it-grows-again">Cool the representation before it grows again</h2>
<div class="dense-cooling-animation">
<div class="cool-stage hot">
<span>DENSE BLOCK OUTPUT</span>
<div class="cool-bank">
<i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i>
</div>
<strong><span class="math inline">\(C\)</span> channels</strong><small>many reusable activations</small>
</div>
<b class="cool-arrow fragment">→</b>
<div class="cool-stage compressed fragment">
<span>1 × 1 CONV</span>
<div class="cool-bank">
<i></i><i></i><i></i><i></i>
</div>
<strong><span class="math inline">\(\lfloor\theta C\rfloor\)</span></strong><small><span class="math inline">\(0\lt\theta\leq1\)</span> controls width</small>
</div>
<b class="cool-arrow fragment">→</b>
<div class="cool-stage pooled fragment">
<span>AVG POOL 2 × 2</span>
<div class="cool-bank">
<i></i><i></i><i></i><i></i>
</div>
<strong><span class="math inline">\(H/2\times W/2\)</span></strong><small>less spatial redundancy</small>
</div>
</div>
<div class="dense-regularization-row">
<div class="fragment">
<span>CAPACITY CONTROL</span><strong>Compression prevents uncontrolled channel growth.</strong><small>DenseNet-BC commonly uses transition compression.</small>
</div>
<div class="fragment">
<span>OVERFITTING CONTROL</span><strong>Dropout can mask newly produced features during training.</strong><small>The paper uses dropout on small datasets; augmentation remains essential.</small>
</div>
</div>
<div class="dense-cooling-verdict fragment">
<span>DO NOT CONFUSE THEM</span><strong>Compression makes the network smaller; dropout makes feature reliance stochastic.</strong>
</div>
<p class="source-note">
Transition compression and dropout follow the DenseNet training variants in Huang et al. <span class="citation" data-cites="huang2017densenet">(Huang et al. 2017)</span>.
</p>
<div class="notes">
<p>Use “cooling” as a visual metaphor, then make the mechanisms precise. The transition layer first uses a one-by-one convolution to reduce channels by compression factor theta, then average pooling halves the spatial resolution. This controls representation size and computation. It is not identical to regularization: dropout directly combats co-adaptation by randomly masking newly produced features during training. The paper reports dropout for several small-dataset experiments; data augmentation is a complementary data-side intervention rather than a connectivity mechanism.</p>
</div>
</section>
<section id="the-implementation-mirrors-the-equation" class="level2">
<h2 class="anchored" data-anchor-id="the-implementation-mirrors-the-equation">The implementation mirrors the equation</h2>
<div class="dense-code-layout">
<div class="dense-code-map">
<span>CHANNEL ACCOUNTING</span>
<div>
<b>START</b><strong><span class="math inline">\(C_0\)</span></strong>
</div>
<i>+</i>
<div>
<b>LAYER 1</b><strong><span class="math inline">\(k\)</span></strong>
</div>
<i>+</i>
<div>
<b>LAYER 2</b><strong><span class="math inline">\(k\)</span></strong>
</div>
<i>+</i>
<div>
<b>LAYER <span class="math inline">\(L\)</span></b><strong><span class="math inline">\(k\)</span></strong>
</div>
<p>
<span class="math inline">\(C_{out}=C_0+Lk\)</span>
</p>
<p><small><strong>torch.cat</strong> is the architectural operation.</small></p>
</div>
<div class="light-code-editor dense-editor">
<div class="editor-bar">
<span>PYTORCH · DENSE BLOCK</span><strong>densenet.py</strong>
</div>
<pre><code><span class="py-kw">class</span> <span class="py-fn">DenseLayer</span>(<span class="py-mod">nn</span>.<span class="py-call">Module</span>):
    <span class="py-kw">def</span> <span class="py-fn">__init__</span>(<span class="py-self">self</span>, in_ch, growth_rate):
        <span class="py-mod">super</span>().<span class="py-call">__init__</span>()
        <span class="py-self">self</span>.transform = <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(
            <span class="py-mod">nn</span>.<span class="py-call">BatchNorm2d</span>(in_ch), <span class="py-mod">nn</span>.<span class="py-call">ReLU</span>(),
            <span class="py-mod">nn</span>.<span class="py-call">Conv2d</span>(in_ch, growth_rate, <span class="py-num">3</span>,
                      padding=<span class="py-num">1</span>, bias=<span class="py-bool">False</span>))

    <span class="py-kw">def</span> <span class="py-fn">forward</span>(<span class="py-self">self</span>, x):
        new_features = <span class="py-self">self</span>.transform(x)
        <span class="py-kw">return</span> <span class="py-mod">torch</span>.<span class="py-call">cat</span>([x, new_features], dim=<span class="py-num">1</span>)

<span class="py-kw">def</span> <span class="py-fn">dense_block</span>(in_ch, num_layers, k):
    layers = []
    <span class="py-kw">for</span> i <span class="py-kw">in</span> <span class="py-call">range</span>(num_layers):
        layers.<span class="py-call">append</span>(<span class="py-call">DenseLayer</span>(in_ch + i * k, k))
    <span class="py-kw">return</span> <span class="py-mod">nn</span>.<span class="py-call">Sequential</span>(*layers)</code></pre>
</div>
</div>
<div class="dense-code-check fragment">
<span>CHECK</span><strong><code>dense_block(64, 4, 32)</code></strong><b>→</b><strong>64 + 4 × 32 = 192 output channels</strong>
</div>
<p class="source-note">
Compact teaching implementation based on Huang et al. <span class="citation" data-cites="huang2017densenet">(Huang et al. 2017)</span>.
</p>
<div class="notes">
<p>Have students predict the output channel count before revealing the numerical check. DenseLayer receives the accumulated tensor, creates k new maps, and concatenates them with the input along dimension one. Sequential works because each DenseLayer returns the enlarged collective state. The constructor’s in_ch plus i times k is exactly the channel-growth equation translated into code.</p>
</div>
</section>
<section id="feature-reuse-buys-efficiencybut-stores-activations" class="level2">
<h2 class="anchored" data-anchor-id="feature-reuse-buys-efficiencybut-stores-activations">Feature reuse buys efficiency—but stores activations</h2>
<div class="network-audit-prompt">
<span>ARCHITECTURE AUDIT · DENSENET</span><strong>What does preserving every feature buy—and what must remain in memory?</strong>
</div>
<div class="network-synthesis">
<div class="network-ledger network-gains">
<span>MAIN IDEAS</span>
<div>
<b>FEATURE REUSE</b><strong>Every layer can read low- and high-level evidence.</strong><small>Useful maps need not be relearned downstream.</small>
</div>
<div>
<b>SHORT PATHS</b><strong>Features and gradients have many direct routes.</strong><small>Deep supervision emerges without auxiliary heads.</small>
</div>
<div>
<b>NARROW UPDATES</b><strong>Each layer contributes only <span class="math inline">\(k\)</span> new maps.</strong><small>Growth rate separates depth from per-layer width.</small>
</div>
</div>
<div class="network-ledger network-limits fragment">
<span>DRAWBACKS</span>
<div>
<b>ACTIVATION MEMORY</b><strong>Earlier maps must remain available for reuse.</strong><small>Training memory can become the practical bottleneck.</small>
</div>
<div>
<b>CHANNEL GROWTH</b><strong>Concatenation widens the shared state.</strong><small>Transition layers must compress and downsample.</small>
</div>
<div>
<b>DATA MOVEMENT</b><strong>Repeated concatenation is not computationally free.</strong><small>Parameter efficiency does not guarantee fast execution.</small>
</div>
</div>
</div>
<div class="network-next-step fragment">
<span>ARCHITECTURAL LESSON</span><strong>Skip connections decide not only what bypasses layers—but how information is combined.</strong><b>add vs.&nbsp;concatenate</b>
</div>
<p class="source-note">
Synthesis based on Huang et al. <span class="citation" data-cites="huang2017densenet">(Huang et al. 2017)</span>. <a href="https://arxiv.org/abs/1608.06993">Original paper ↗</a>
</p>
<div class="notes">
<p>Ask students to name one benefit and one cost before revealing the right column. Dense connectivity supports feature reuse, short gradient paths, and narrow per-layer contributions. Its main systems cost is activation memory and data movement: earlier features must stay available and the concatenated state grows. Transition layers—typically one-by-one convolution followed by average pooling—control this growth between dense blocks. Close by comparing the combination operators: addition and concatenation express different information-preservation policies.</p>
</div>
</section>
</section>
<section id="the-architecture-toolkit-1" class="level1 section-slide architecture-section closing-section summary-closing" data-section-progress="6 / 7" style="--section-progress:85.714%">
<h1 class="section-slide architecture-section closing-section summary-closing" data-section-progress="6 / 7" style="--section-progress:85.714%">06 · The architecture toolkit</h1>
<div class="toolkit-prompt">
<span>DO NOT MEMORIZE FIVE NETWORKS</span><strong>Remember five reusable operations—and the pressure each one answers.</strong>
</div>
<div class="architecture-toolkit">
<div class="tool-card vgg-tool fragment">
<span>VGG</span>
<div class="tool-icon repeat-icon">
<i></i><i></i><i></i>
</div>
<strong>REPEAT</strong><small>Build depth from uniform small-kernel blocks.</small><b>cost · compute</b>
</div>
<div class="tool-card nin-tool fragment">
<span>NiN</span>
<div class="tool-icon mix-icon">
<i></i><em>1×1</em><i></i>
</div>
<strong>MIX CHANNELS</strong><small>Learn nonlinear combinations at each location.</small><b>gain · compact head</b>
</div>
<div class="tool-card inception-tool fragment">
<span>INCEPTION</span>
<div class="tool-icon branch-icon">
<i></i><i></i><i></i>
</div>
<strong>BRANCH</strong><small>Process several spatial scales in parallel.</small><b>cost · complexity</b>
</div>
<div class="tool-card resnet-tool fragment">
<span>RESNET</span>
<div class="tool-icon add-icon">
<i></i><em>+</em>
</div>
<strong>ADD</strong><small>Learn a correction while preserving an identity path.</small><b>gain · optimization</b>
</div>
<div class="tool-card dense-tool fragment">
<span>DENSENET</span>
<div class="tool-icon concat-icon">
<i></i><i></i><i></i><i></i>
</div>
<strong>CONCATENATE</strong><small>Expose every earlier feature for explicit reuse.</small><b>cost · memory</b>
</div>
</div>
<div class="toolkit-axis fragment">
<span>THE COMMON QUESTION</span><strong>What should the next layer receive?</strong><b>one output · many scales · an identity · or the full history</b>
</div>
<div class="notes">
<p>Reveal the cards one at a time and ask students to supply the verb before it appears. Each historical network contributes a transferable operation rather than a complete recipe that must be copied wholesale. VGG contributes disciplined repetition, NiN local channel mixing, Inception parallel scales, ResNet additive correction, and DenseNet explicit feature reuse. Keep the cost visible because architecture design always trades one pressure for another.</p>
</div>
</section>
<section id="compose-for-the-task" class="level1 section-slide architecture-section closing-section composition-closing" data-section-progress="7 / 7" style="--section-progress:100%">
<h1 class="section-slide architecture-section closing-section composition-closing" data-section-progress="7 / 7" style="--section-progress:100%">07 · Compose for the task</h1>
<div class="task-specification">
<span>DESIGN BRIEF</span><strong>Classify plant disease from mobile images</strong>
<div>
<b>small lesions</b><b>limited compute</b><b>deep training must stay stable</b><b>10 classes</b>
</div>
</div>
<div class="composed-network">
<div class="composition-step fragment">
<span>STEM</span><strong>VGG idea</strong><small>repeat padded <span class="math inline">\(3\times3\)</span> convolutions</small>
</div>
<b class="fragment">→</b>
<div class="composition-step fragment">
<span>LOCAL DETAIL</span><strong>Inception idea</strong><small>branch across receptive-field sizes</small>
</div>
<b class="fragment">→</b>
<div class="composition-step fragment">
<span>DEEP FLOW</span><strong>ResNet idea</strong><small>add identity shortcuts</small>
</div>
<b class="fragment">→</b>
<div class="composition-step fragment">
<span>HEAD</span><strong>NiN idea</strong><small>class maps + global average pooling</small>
</div>
</div>
<div class="design-rejection fragment">
<span>WHY NOT EVERYTHING?</span><strong>Dense concatenation is useful, but its activation-memory cost conflicts with the mobile constraint.</strong>
</div>
<div class="design-logic fragment">
<div>
<span>SPECIFICATION</span><strong>What must the model do?</strong>
</div>
<b>→</b>
<div>
<span>PRESSURE</span><strong>What will fail first?</strong>
</div>
<b>→</b>
<div>
<span>MECHANISM</span><strong>Which technique addresses it?</strong>
</div>
<b>→</b>
<div>
<span>EVIDENCE</span><strong>Did the experiment improve?</strong>
</div>
</div>
<div class="final-lecture-question fragment">
<span>LEAVE WITH THIS</span><strong>A network is not a historical name. It is a composition of mechanisms chosen for a task.</strong>
</div>
<div class="notes">
<p>Give students the design brief and ask which techniques they would combine before revealing the proposed network. The answer deliberately borrows from four families: VGG repetition for a regular stem, Inception branching for small lesions at different scales, ResNet shortcuts for stable depth, and NiN’s global-average-pooling head for a compact classifier. DenseNet is not “bad”; it is rejected here because the task says mobile compute and activation memory matter. End with the design loop: specification, pressure, mechanism, evidence. Students should leave prepared to build hybrids rather than choose architecture names from a menu.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/anassbelcaid\.github\.io\/deeplearning-course\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Deep Learning · ENSA Tétouan</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>